### ISSUE TITLE
FPS issues

### ISSUE THREAD

**Issue by Krysommor** [b0bst3r/BTM#1]
Tried to load your pack for the first time today and all I got was 1-2 fps, I have 4Gb ram dedicated to it through the ATLauncher but nothing. I have even tried updating java and even tried lowering setting but to no avail. even optifine could not help me. any tips?
PC Spec:
AMD FX 8370
16GB Ram
MSI Radeon RX470 Twin Frozr VI
Win 10 x64 Bit
Java 1.8.0_144 x64

**Comment by b0bst3r** [comment]
Give it more RAM 1.12 is hungry, low FPS is a side effect of running out of RAM assigned to Java.  I run with 6GB RAM.

**Comment by Krysommor** [comment]
I have tried with 8GB and 10GB ram but did not help.
Seed: 5932531184360842308

**Comment by Krysommor** [comment]
just tried server to see if it was going to be client side only but looking through the log I see " [Server thread/WARN] [FML]: Binnie Core loaded a new chunk (-1, 2  Dimension: 0) during chunk population, causing cascading worldgen lag. Please report this to the mod's issue tracker. This log can be disabled in the Forge config."  Could this be the issue that my SP could be having?

**Comment by Krysommor** [comment]
http://paste.atlauncher.com/view/ee555263
[https://imgur.com/a/Fs77w](url)
https://github.com/ForestryMC/Binnie/issues/301 <<<<might be the issue

**Comment by Krysommor** [comment]
@b0bst3r

**Comment by b0bst3r** [comment]
Not that's normal and will not cause FPS issues.  FPS is caused by too much updating of blocks or liquids in the world, quick question do you use any resourcepacks?

**Comment by Krysommor** [comment]
I do not use resoucepacks and have tried every trick in the book. The only way I got it to run was removing Binnies mod, after that I have a reasonable fps

**Comment by Krysommor** [comment]
just to add this is opening a new world, even saving and re-opening does not help.
I did make a video to show you but the upload was taking too long.

**Comment by Krysommor** [comment]
http://paste.atlauncher.com/view/0b0f90f4
Here is something you might like to see.
I added Optifine to see what was going on and I found it.

**Comment by Krysommor** [comment]
All thanks to the DNS forum the Issue was due to me having AMD not Intel
@b0bst3r please could you add Optifine to the Optional DLC
After installing Optifine and disabling terrain animation I have 60+ FPS
