### ISSUE TITLE
Skillable mod max level set to 5

### ISSUE THREAD

**Issue by smithy24** [b0bst3r/BTM#4]
There are no perks at level 5, so why use the mod at all?

**Comment by b0bst3r** [comment]
Skillable skills are not used, the mod is used to lock other mods stopping Better With Mods bypasses, it's how Actually additions and other mods are locked behind getting to the End.

I did a lot of testing with skillable and Better with Mods and enabling the skills was very very brutal, so much so no one would have played the pack at all.

**Comment by b0bst3r** [comment]
Removed skills tab in 3.7.0
