### ISSUE TITLE
Balancing: Erse

### ISSUE THREAD

**Issue by smithy24** [b0bst3r/BTM#5]
These Erses (Strawberries) from futurepack should not be plantable. They drop ~4 pieces and restore ~3 hunger.

**Comment by b0bst3r** [comment]
Yeah I wish I could change this

**Comment by b0bst3r** [comment]
https://github.com/mcenderdragon/Futurepack-API/issues/352

**Comment by b0bst3r** [comment]
Nerfed the Erse in 3.7.0
