### ISSUE TITLE
Balancing: Magnetite

### ISSUE THREAD

**Issue by smithy24** [b0bst3r/BTM#6]
Magnetite gives you 4 iron ingots in a vanilla furnace. This  is probably not intended.

**Comment by b0bst3r** [comment]
A futurepack update broke this, logging with them.

**Comment by b0bst3r** [comment]
https://github.com/mcenderdragon/Futurepack-API/issues/351

**Comment by b0bst3r** [comment]
Fixed in 3.6 (coming shortly)
